services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-wordpress.cxyow8s4km5z.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: giovana
      WORDPRESS_DB_PASSWORD: teste123
      WORDPRESS_DB_NAME: db_wordpress
    networks:
      - rede
    volumes:
      - /home/ec2-user/mnt/wordpress:/var/www/html


networks:
  rede:
   driver: bridge