services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: endpoint do rds
      WORDPRESS_DB_USER: nameUser
      WORDPRESS_DB_PASSWORD: passwordUser
      WORDPRESS_DB_NAME: nameDB
    networks:
      - rede
    volumes:
      - /home/ec2-user[sua pasta]:/var/www/html


networks:
  rede:
   driver: bridge